FROM registry.redhat.io/rhel9/redis-6@sha256:1e80ba177cfe02a602d8672050051a0a092fba1dd199b2a245d94bef4e3c989b

LABEL description="Securesign redis is built ontop of rhel9/redis-6 but accepts external connections and runs appendonly mode with full durability."
LABEL io.k8s.description="Securesign redis is built ontop of rhel9/redis-6 but accepts external connections and runs appendonly mode with full durability."
LABEL io.k8s.display-name="redis container image for Red Hat trusted artifact signer."
LABEL io.openshift.tags="redis, Red Hat trusted artifact signer."
LABEL summary="Runs redis in appendonly mode with enablement for external connections by default."
LABEL com.redhat.component="redis"
LABEL name="redis"

USER 1001

RUN sed -i 's/#bind 127.0.0.1 -::1/bind 0.0.0.0/g' /etc/redis/redis.conf && sed -i 's/appendonly no/appendonly yes/g' /etc/redis/redis.conf

ENTRYPOINT ["container-entrypoint"]
CMD ["run-redis"]
